### ISSUE TITLE
Setup DNS/Hosting https://livepage.mikerogers.io/ 

### ISSUE THREAD

**Issue by MikeRogers0** [MikeRogers0/LivePage-landing#1]
I'm thinking S3 + CloudFront should be suitable.

**Comment by andyrichardson** [comment]
I've never used the amazon services so I can't comment on them much. I usually use a linux server on digital ocean for small projects/websites. The $5/month option would be more than sufficient for this. 

How much does S3 and CloudFront set you back? What are the advantages?

Edit: how about https://pages.github.com/

**Comment by MikeRogers0** [comment]
S3 + CloudFront costs <£1 a year (I use it for https://github.com/MikeRogers0/MikeRogersIO ). It's a bit like GH Pages, but we build locally so we can make use of any weird ruby gems.

**Comment by andyrichardson** [comment]
Wow that's cheap. Do you have a domain?

**Comment by MikeRogers0** [comment]
It's an awesome setup for sites that'll only change a little :)

I was thinking of just a subdomain like `https://livepage.mikerogers.io/`, most the dedicated domains seem like overkill.

**Comment by andyrichardson** [comment]
I think thats the best shout. It'll get that Mike Rogers branding out there too!

**Comment by MikeRogers0** [comment]
https://livepage.mikerogers.io/ - Done :)

**Comment by andyrichardson** [comment]
Looks good!
