### ISSUE TITLE
Favicon

### ISSUE THREAD

**Issue by MikeRogers0** [MikeRogers0/LivePage-landing#4]
Add in a favicon

**Comment by andyrichardson** [comment]
Do you want the LivePage logo with a white backdrop as the favicon?

**Comment by andyrichardson** [comment]
Created a favicon branch. 

Despite _favicon.png_ being in the root of the build directory, requesting _/favicon.png_ will result in a 404. Mind taking a look? I assumed everything in the build directory was public but that doesn't seem to be the case.

**Comment by MikeRogers0** [comment]
https://github.com/MikeRogers0/LivePage-landing/commit/a32d768127acb699bc519b7d085740cf51898d18 - It needed to be outside of the build specific block :) 

How are you finding middleman?

**Comment by andyrichardson** [comment]
> How are you finding middleman? 

Haven't played around much - seems okay though. Check out the comment on https://github.com/MikeRogers0/LivePage-landing/commit/a32d768127acb699bc519b7d085740cf51898d18 and let me know whats up.

**Comment by andyrichardson** [comment]
Favicon merged with master.
